### ISSUE TITLE
Respawning after death sometimes puts you under the map

### ISSUE THREAD

**Issue by Leafy-Greens** [KosmosisDire/TeammateRevive#31] opened 2022-03-15 13:16 UTC
This happened a lot during my run yesterday with my friends, where respawning you wouldn't put you near the origin point of your death, and instead would teleport you under the map
Under certain cases this was fine and recoverable, but since we went into the void fields, it made reviving someone impossible without running debug commands.

**Comment by KosmosisDire** [comment] 2022-03-18 23:18
Hey! Thanks for the report. I am not able to reproduce this issue. Could you list what other mods you are using? Have you tried with only this mod to see if it is actually causing the problem? Also, could you upload the logs next time you get the chance? Thanks!

**Comment by KosmosisDire** [comment] 2022-04-17 19:31
Closing as I don't have enough info to do anything about this

**Closed by KosmosisDire** 2022-04-17 19:31 UTC
